version: '3'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Asher@123
      MYSQL_DATABASE: turf_booking
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the init.sql here
  
  web:
    build: .
    ports:
      - "5001:5000"
    depends_on:
      - db
    environment:
      FLASK_ENV: development

volumes:
  db_data:
